version: '3'
services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3
    networks:
      - arango-network

volumes:
  arango_data:

networks:
  arango-network:
    driver: bridge